version: "3.7"

services:
  laravel-app:
    build:
      context: .
      args:
        uid: ${UID}
    container_name: laravel-app
    ports:
      - 8000:80
    restart: always
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql-db
    networks:
      backend:
        aliases:
          - app

  mysql-db:
    image: mariadb:10.4.11
    container_name: mysql-db
#    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

    networks:
      backend:
        aliases:
          - mysql-db
  php-myadmin:
    image: adminer:latest
    restart: always
    container_name: phpmyadmin
    ports:
      - 8080:8080
    depends_on:
      - mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      backend:
        aliases:
          - php-myadmin

networks:
  backend:
    name: backend-network
